import requests
import pandas as pd
import time
import os
from tqdm import tqdm
import json

# configuration:

# input csv created by the main crawler
GAMES_CSV = "games.csv" 
# directory for intermediate enriched game metadata
CHECKPOINT_DIR = "checkpoint_games"
# delay between steam store api requests
RATE_LIMIT = 0.5 
# save progress every n processed games
CHECKPOINT_INTERVAL = 50 
# create checkpoint directory if it does not exist
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# load game list
# read appids and user counts generated by the crawler
games_df = pd.read_csv(GAMES_CSV)
# keep only one row per appid
games_df = games_df.drop_duplicates(subset="appid")

# define checkpoint file paths
checkpoint_file = os.path.join(CHECKPOINT_DIR, "enriched_games.csv")
visited_file = os.path.join(CHECKPOINT_DIR, "visited_games.json")

# initialize empty dataframe for enriched game metadata
enriched_df = pd.DataFrame(columns=["appid", "name", "genres", "developer", "publisher",
                                    "platforms", "release_date", "user_count"])
# initialize set of already processed appids
visited_appids = set()

# load existing enriched metadata if checkpoint exists
if os.path.exists(checkpoint_file):
    enriched_df = pd.read_csv(checkpoint_file, sep=";", quoting=1)

# load already processed appids if checkpoint exists
if os.path.exists(visited_file) and os.path.getsize(visited_file) > 0:
    try:
        with open(visited_file) as f:
            visited_appids = set(int(a) for a in json.load(f))
        tqdm.write(f"Resuming from checkpoint, {len(visited_appids)} games already processed")
    except Exception:
        tqdm.write("Warning: visited_games.json corrupted, starting fresh")

# main loop over all games
for idx, row in tqdm(games_df.iterrows(), total=len(games_df),
                      desc="Fetching game metadata", ncols=100):

    appid = int(row["appid"])  # ensure it's a plain int
    # keep popularity count from the crawler output
    user_count = row["user_count"]

    # skip games that were already processed in a previous run
    if appid in visited_appids:
        continue 

    # steam store api endpoint for game details
    url = f"https://store.steampowered.com/api/appdetails?appids={appid}"

    try:
        # request game metadata from steam store api
        r = requests.get(url, timeout=10)
        # parse json response
        data = r.json()
        # skip appids without successful metadata response
        if not data[str(appid)]["success"]:
            continue
        # extract metadata dictionary for this game
        info = data[str(appid)]["data"]

        # extract game name
        name = info.get("name")
    
        # extract and join game genres
        genres = ";".join([g["description"] for g in info.get("genres", [])]) if info.get("genres") else ""
        # extract and join developer names
        developer = ";".join(info.get("developers", [])) if info.get("developers") else ""
        # extract and join publisher names
        publisher = ";".join(info.get("publishers", [])) if info.get("publishers") else ""
        # extract supported platforms
        platforms = ";".join([k for k,v in info.get("platforms", {}).items() if v]) if info.get("platforms") else ""
        # extract release date
        release_date = info.get("release_date", {}).get("date", "")

        # replace tab characters to avoid csv formatting issues
        for col in ["genres", "developer", "publisher", "platforms"]:
            val = locals()[col]
            locals()[col] = val.replace("\t", ";") if val else val

        # append enriched metadata for this appid
        enriched_df = pd.concat([enriched_df, pd.DataFrame([{
            "appid": appid,
            "name": name,
            "genres": genres,
            "developer": developer,
            "publisher": publisher,
            "platforms": platforms,
            "release_date": release_date,
            "user_count": user_count
        }])], ignore_index=True)

        # mark appid as processed
        visited_appids.add(appid)

    except Exception as e:
        # keep the script running even if one appid fails
        print(f"Error fetching {appid}: {e}")

    # save checkpoint periodically to protect progress
    if len(visited_appids) % CHECKPOINT_INTERVAL == 0:
        enriched_df.to_csv(checkpoint_file, sep=";", index=False, quoting=1)
        with open(visited_file, "w") as f:
            json.dump([int(a) for a in visited_appids], f)

    # wait before next request to reduce api pressure
    time.sleep(RATE_LIMIT)

# save final enriched metadata
enriched_df.to_csv(checkpoint_file, sep=";", index=False, quoting=1)
# save final list of processed appids
with open(visited_file, "w") as f:
    json.dump([int(a) for a in visited_appids], f)

tqdm.write("Finished!")